version: '2'

services:

  web:
    build: ./
#   Ne pas exposer le service, il faut passer par le load balancer
#    ports:
#      - 5000:5000
    labels:
      - "traefik.frontend.rule=Host:whoami.docker.localhost"
    networks:
    - app-network
    depends_on:
    - redis

  redis:
    image: "redis:alpine"
    volumes:
    - redis-vol:/data
    networks:
    - app-network

  lb:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Tr√¶fik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080"   # GUI
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
    - app-network

networks:
  app-network:

volumes:
  redis-vol: